### Teste local: /credito, 200 OK

GET http://localhost:3000/api/v1/credito HTTP/1.1
content-type: application/json

{
  "id": "0001",
  "senha": "1234",
  "jogo": "0001",
  "valor": "150"
}

### Teste remoto: /credito, 200 OK

GET https://feira-de-jogos.sj.ifsc.edu.br/api/v1/credito HTTP/2.0
content-type: application/json

{
  "id": "0001",
  "senha": "1234",
  "jogo": "0001",
  "valor": "150"
}

### Teste local: /credito, 400 Bad Request

GET http://localhost:3000/api/v1/credito HTTP/1.1
content-type: application/json

{
  "apelido": "boi",
  "senha": "1234",
  "jogo": "0001",
  "valor": "150"
}

### Teste remoto: /credito, 400 Bad Request

GET https://feira-de-jogos.sj.ifsc.edu.br/api/v1/credito HTTP/2.0
content-type: application/json

{
  "apelido": "boi",
  "senha": "1234",
  "jogo": "0001",
  "valor": "150"
}

### Teste local: /credito, 401 Unathorized

GET http://localhost:3000/api/v1/credito HTTP/1.1
content-type: application/json

{
  "id": "0001",
  "senha": "123456",
  "jogo": "0001",
  "valor": "150"
}

### Teste remoto: /credito, 401 Unathorized

GET https://feira-de-jogos.sj.ifsc.edu.br/api/v1/credito HTTP/2.0
content-type: application/json

{
  "id": "0001",
  "senha": "123456",
  "jogo": "0001",
  "valor": "150"
}

###
