### Teste local: /extrato, 200 OK

GET http://localhost:3000/api/v1/extrato HTTP/1.1
content-type: application/json

{
  "id": "0001",
  "senha": "1234"
}

### Teste remoto: /extrato, 200 OK

GET https://feira-de-jogos.sj.ifsc.edu.br/api/v1/extrato HTTP/2.0
content-type: application/json

{
  "id": "0001",
  "senha": "1234"
}

### Teste local: /extrato, 400 Bad Request

GET http://localhost:3000/api/v1/extrato HTTP/1.1
content-type: application/json

{
  "apelido": "boi",
  "senha": "1234"
}

### Teste remoto: /extrato, 400 Bad Request

GET https://feira-de-jogos.sj.ifsc.edu.br/api/v1/extrato HTTP/2.0
content-type: application/json

{
  "apelido": "boi",
  "senha": "1234"
}

### Teste local: /extrato, 401 Unathorized

GET http://localhost:3000/api/v1/extrato HTTP/1.1
content-type: application/json

{
  "id": "0001",
  "senha": "123456"
}

### Teste remoto: /extrato, 401 Unathorized

GET https://feira-de-jogos.sj.ifsc.edu.br/api/v1/extrato HTTP/2.0
content-type: application/json

{
  "id": "0001",
  "senha": "123456"
}

###
